services:
  codexchat_front:
    container_name: codexchat_front
    build:
      context: ./codexchat_front
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - n8n_default
    labels:
      - traefik.enable=true
      - traefik.docker.network=n8n_default
      - traefik.http.routers.codexchat-front.entrypoints=web,websecure
      - traefik.http.routers.codexchat-front.rule=Host(`questflow.net`) || Host(`www.questflow.net`) || Host(`todo.flounderboard.com`)
      - traefik.http.routers.codexchat-front.priority=200
      - traefik.http.routers.codexchat-front.tls=true
      - traefik.http.routers.codexchat-front.tls.certresolver=mytlschallenge
      - traefik.http.services.codexchat-front.loadbalancer.server.port=3000

networks:
  n8n_default:
    external: true
